language: python
python:
 - 3.6

sudo: required

cache: pip

addons:
  apt:
    packages:
      - libssl-dev
      - python3-dev

before_install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/coala/coala#egg=coala
  - pip install git+https://github.com/coala/coala-bears#egg=coala-bears

script:
  - coala --non-interactive -V
  - python -m pytest --cov=plugins --cov-report term-missing tests
  - codecov

notifications:
  email: false
